### ISSUE TITLE
Search & Replace text

### ISSUE THREAD

**Issue by locvfx** [GoogleChromeLabs/text-app#297] opened 2016-08-17 02:02 UTC
Yes, there is a search input but we really need a **Search&Replace** !
Btw, the app is well designed. I really love it.

**Comment by smdvmx** [comment] 2016-09-10 00:01
search and replace is critical. We often search for a large bloc of text/code and replace it with another large block of text/code with the modifications needed. It's much simpler and faster than some ridiculous CMS. So please yes include that.

**Comment by henrywright** [comment] 2016-10-08 20:43
#285

**Comment by BugsNash** [comment] 2018-06-18 04:14
Duplicate of #121

**Closed by BugsNash** 2018-06-18 04:14 UTC
