### ISSUE TITLE
Printing Issues

### ISSUE THREAD

**Issue by markgluth** [GoogleChromeLabs/text-app#495] opened 2020-02-09 05:18 UTC
When attempting to print from text, it does not load the entire document.  It will load the entire page range (for instance 1-4) but only a portion of the pages will be loaded (for instance 1-2.5). This is true for both the print preview, as well as  what is actually printed.  This is true if printing to a printer, or priting to a pdf.

**Comment by BugsNash** [comment] 2020-02-09 19:02
Duplicate of #447

**Closed by BugsNash** 2020-02-09 19:02 UTC
