### ISSUE TITLE
Auto-save backup files

### ISSUE THREAD

**Issue by johnstultz-work** [GoogleChromeLabs/text-app#290] opened 2016-01-21 04:42 UTC
It would be very nice if it auto-saved backup files for any unsaved files. I find myself losing data quite often when I reset to upgrade or shut the machine down, or otherwise accidentally close the window without saving.

**Comment by tamboril** [comment] 2017-09-08 16:58
Yep.  I really like the app.  First thing I noticed is lack of recovery.
The app needs to "just work" if Chrome is closed, if the window is closed, or if the machine is rebooted.

**Comment by BugsNash** [comment] 2018-06-18 03:41
Part of this issue (closing window without saving) was fixed in #336. Auto saving when machine is shut down or otherwise force quit remains an issue.

**Comment by BugsNash** [comment] 2018-06-19 04:31
Duplicate of #20

**Closed by BugsNash** 2018-06-19 04:31 UTC
Labels: feature
