### ISSUE TITLE
Rename "click function"

### ISSUE THREAD

**Issue by wotgl** [GoogleChromeLabs/text-app#252] opened 2014-10-16 16:39 UTC
Hello! 
Great app, use it actively in ChromOS. I guess my post is more to the topic "suggestions and comments", but: why not make the function rename the text file directly by clicking on it's name in the header? I think it would be very convenient c: 
_click - enter new name - profit_
Thanks!

**Comment by BugsNash** [comment] 2018-06-01 05:13
duplicate of #104 

glad you like the app :)

**Closed by BugsNash** 2018-06-01 05:13 UTC
