### ISSUE TITLE
chromebook shut down, lost unsaved text

### ISSUE THREAD

**Issue by wizardlizard12** [GoogleChromeLabs/text-app#455] opened 2019-03-11 21:57 UTC
hi! my computer shutdown out of nowhere yesterday and i lost my unsaved files. is there any way i can get them back?

**Comment by BugsNash** [comment] 2019-03-11 22:51
Sorry we currently do not support automatic caching of unsaved changes :(

Duplicate of #20

**Comment by wizardlizard12** [comment] 2019-03-11 23:27
oh :( well thanks anyway!

**Closed** 2019-03-12 00:59 UTC
