### ISSUE TITLE
slow scrolling jumps backward

### ISSUE THREAD

**Issue by eritain** [GoogleChromeLabs/text-app#303] opened 2017-02-16 20:09 UTC
Quick scrolling is able to move through documents -- ballistic scrolling, where the document continues moving after my fingers have left the touchpad. But below a certain speed, scrolling is just spinning my wheels: after scrolling through about a screenful of content, the screen jumps back to approximately the same line it started on. Sometimes further than where it started.

The jump is reflected across the UI: the box in the scroll bar pops back to its original position as though on a spring, and the line numbers and line content jump back too. 

The jumping-back phenomenon is also visible in the scroll box during the later portion of long ballistic scrolls.

**Comment by ste4es** [comment] 2017-03-03 12:54
Same issue.  Seems to have coincided with a recent ChromeOS update.
Linux localhost 3.10.18 #1 SMP Wed Feb 22 23:32:23 PST 2017 x86_64 Intel(R) Celeron(R) CPU N2840 @ 2.16GHz GenuineIntel GNU/Linux

**Comment by danhab99** [comment] 2017-03-20 14:01
This is beyond reason, I have to scroll slowly with the arrow keys. I have no idea how this extension even works to fix it myself.

**Comment by murthag11** [comment] 2017-04-22 08:50
Same here. I'd love this to get fixed, it's the nicest Editor on ChromeOS imo.
Luckily, i can scroll with the Touchscreen (Pixel 2025), but sometimes when I click in a line to write there, it also jumps somewhere and only refocuses when I start typing.

**Comment by Sputternik** [comment] 2017-04-26 17:51
I'd appreciate a fix for this too. I agree with murthag11, this IS the nicest, and cleanest editor on ChromeOS. I am using Carat for the time being, but the feature implementation on Editor is better/cleaner, and Caret can't print without line numbers (at least, I have not had luck determining js code to suppress them on the printout). So I much prefer Editor. A big Thank You to the developer!

**Comment by synthstow** [comment] 2017-06-26 04:16
I have this too, extremely irritating

**Comment by josephrocca** [comment] 2017-09-04 14:38
This editor is basically unusable with this bug. Any hope of this being fixed any time soon @eterevsky? Is it being maintained? Such a nice little app otherwise - would love to keep it as my default editor.

**Comment by danhab99** [comment] 2017-09-08 15:38
@josephrocca I've stopped completely. I new use Caret!

**Comment by bawden** [comment] 2017-10-11 06:29
The most recent ChromOS upgrade installed this editor as if Google thinks it actually works, but the scrolling problem make it almost worthless.  What were they thinking!?

**Comment by SiebertBrandon** [comment] 2017-11-13 18:34
Confirmed this is occurring for me as well. The view bounces back when scrolling with the track pad. It seems to be independent of what line currently has the cursor.

Chrome OS Version 64.0.3261.0 (Official Build) dev (64-bit)
Acer Chromebook 14
Text App version 0.5.68

**Comment by DefecateRainbows** [comment] 2017-12-16 17:25
Happens here too.

**Comment by ammaarpatel99** [comment] 2018-01-01 10:57
This is a real problem and happens unless scrolling really fast, which is pretty useless as scrolling that fast only allows you to go from the top of a website to the bottom, and nowhere in between.

**Comment by JerryWiltz** [comment] 2018-01-11 00:27
Happens here too. If I scroll fast it, gets down to the bottom. But if I scroll slow, it bounces back up. Very frustrating.

**Comment by tomohaha3** [comment] 2018-01-30 19:11
bump

**Comment by ButteryRolls** [comment] 2018-02-05 03:14
bump

**Comment by SHADOWELITE7** [comment] 2018-02-05 15:25
you know they aren't going to update the text editor

**Comment by DefecateRainbows** [comment] 2018-02-05 15:26
Well this is GitHub, for god's sake.
I'll make a fork of the code, when I hate time.
There might already be one.

**Comment by SHADOWELITE7** [comment] 2018-02-05 15:30
@DefecateRainbows what 3d modeller do you use? it looks nice tbh

**Comment by DefecateRainbows** [comment] 2018-02-05 15:31
Feel free to start your own in the meantime, it'll be some time before my fork is finished.
Just Blender!
... did you google my profile picture to see if it was original lol?
I actually put it on opengameart
https://opengameart.org/content/low-poly-knight

**Comment by SHADOWELITE7** [comment] 2018-02-05 15:34
thx

**Comment by tac11tac** [comment] 2018-02-27 19:43
I am having this issue, also.  It is particularly obnoxious when using a scroll mouse.  I've not seen it with my touchpad or touchscreen.

**Comment by Mythius** [comment] 2018-03-04 21:29
This happens for me as well.
Only thing I can do is use right hand side scroll bar.

**Comment by KidneyPunch** [comment] 2018-03-28 14:20
This is super frustrating to have jump all over the place, then try to find where your cursor is.  I wasn't a huge fan of Carat, but if someone has another editor they recommend I'd love to try it out.

**Comment by GitBoudewijn** [comment] 2018-05-18 16:33
This issue makes this app almost unusable with large files.

**Comment by oliversiegel** [comment] 2018-06-12 00:14
Me too

**Comment by BugsNash** [comment] 2018-06-18 04:48
Can reliably repro with both mouse and touchpad on chromeos. When scrolling slowly from the top at around line 38 it jumps back to around line 10.

**Comment by BugsNash** [comment] 2018-06-22 04:17
This seems to be caused by the CodeMirror library we're using. It seems the latest version of CodeMirror (5.39.0) doesn't have this issue, so updateing the CodeMirror library should fix the problem.

**Comment by GitBoudewijn** [comment] 2018-06-25 01:00
Any idea when this will be updated? It would be nice to be able to use this app again after more than a year.

**Comment by BugsNash** [comment] 2018-06-25 01:06
Hopefully on the order of weeks? Working on it now, there are a few issues with hard coded links to stuff that no longer exists and changes we've made to the version of the library that we use.

This will also require some QA testing (which I will send to another team) before uploading the new version of CodeMirror to make sure I didn't miss anything that is broken by the update (I've found 1 thing that breaks with the new version so far), so it depends how long that will take.

**Comment by BugsNash** [comment] 2018-06-28 03:15
Blocked on #352

**Closed** 2018-07-17 02:54 UTC
Labels: blocked, bug

**Comment by BugsNash** [comment] 2018-07-17 07:16
An updated version of the app with this bug fixed has been pushed to the web store.
