### ISSUE TITLE
Opening files created in Text on Notepad

### ISSUE THREAD

**Issue by TeschMatthew64** [GoogleChromeLabs/text-app#452] opened 2019-02-13 16:39 UTC
I was writing a batch file on this app, and transferred it to a Windows computer to run the program. I ran the program, and it worked perfectly. I then went to edit the code, and all of my code was in one giant block instead of being on separate lines as it showed up in the Text app. The damage was reversible, but it took a while seeing as it was over 300 lines of code. This is the only issue I have ever had with this app, and if you could fix this I would be very happy with this app.

**Comment by BugsNash** [comment] 2019-02-15 00:47
Hi TeschMatthew64

This is likely due to the different line ending encodings in windows vs unix. You would have the same issue if you created the file in any other program on ChromeOs, Mac, or Linux then opened it on a Windows machine. There are applications available to convert line endings between Unix/Windows. Hope that helps.

Duplicate of #300

**Closed by BugsNash** 2019-02-15 00:47 UTC
