### ISSUE TITLE
Autosave Feature needed

### ISSUE THREAD

**Issue by jokerkeny** [GoogleChromeLabs/text-app#456] opened 2019-04-14 18:21 UTC
Hello

Even though there is a warning for unsaved progress [#336](https://github.com/GoogleChromeLabs/text-app/pull/336#issue-189285831), I still accidentally closed unsaved files several times, as a heavy Pixelbook user.
That's because Pixelbook has many unwanted accidents, such as switch off the computer automatically which would also close the unsaved files in **Text**. (Pixelbook doesn't sleep when closing the lid, just like a tablet)

And there is also a bug for this warning feature:
When I press Shift+W twice, the warning window would be closed, together with the unsaved file.

Auto-save is mostly designed for these "crashed" situations, and there are always accidents we haven't considered ahead.

For autosave, I suggest creating temporary just for unsaved files, like the vim swap file. (which should also include the untitled ones), and automatically open these when user launch **Text** again.

For many people, the most convenient method to take down some note is to open a text editor, which is **Text** for chrome os. (And I think that's why Windows default editor is named **notepad**) Because of this easy accidentally closing issue, I considered switching to **Keep**, but Keep is not fast as **Text**, and it has some synchronize issue. In addition, there are some **Text** exclusive features.

**Comment by BugsNash** [comment] 2019-04-14 22:22
Autosave request is duplicate of #20.

Opening new issue for ctrl+shift+w twice problem to keep it separate from auto save.

**Closed by BugsNash** 2019-04-14 22:22 UTC
