### ISSUE TITLE
Ctrl+S being different from Ctrl+s doesn't make any sense

### ISSUE THREAD

**Issue by varunarora** [GoogleChromeLabs/text-app#523] opened 2020-10-04 18:42 UTC
Ctrl+s and Ctrl+S do different things.

https://github.com/GoogleChromeLabs/text-app/blob/04781046993a69c603bc4b6ac37b2ede743c42dd/js/controllers/hotkeys.js#L64-L70

As a user, I thought this was a bug that will go away. In all my time of using tools like Notepad, Sublime, Atom, Eclipse, etc. etc., I have never had to always uncapitalize before saving, so that I didn't "save as...". Why break the normal? Is there a reason this change was introduced? Which text editor follows this pattern?

Easily the most annoying thing to me as an active user of the tool. I know the fix is easy, but I didn't just want to submit a PR, because I don't know why it was introduced.

**Comment by Mystael** [comment] 2020-10-05 21:03
I believe this shortcut combination is a way to implement `Ctrl+Shift+s`, which is quite standard way to _save file as_.
While it may bring you some difficulties during saving the files with `Caps Lock` turned on, you can still press pretty much the same shortcut combination to save file in a standard way as `Ctrl+Shift+s` (ergo `Ctrl+S`) with `Caps Lock` turned on translates into `Ctrl+s`. Proved & tested.

**Comment by varunarora** [comment] 2020-10-07 23:50
@Mystael That's right. But these two are not the same. The keybindings should explicitly look for `Ctrl+Shift+s` as opposed to being in `Caps Lock` mode (I am using the Chromebook setting where you can switch the search button to be a `Caps Lock` button) and pressing `Ctrl+s`. `Caps Lock` mode is not a `Shift`.

I am sure Chrome gives this information to the apps.

**Comment by varunarora** [comment] 2020-12-13 03:36
Thank you, @Mystael!

**Comment by mercmobily** [comment] 2022-06-08 14:39
I think this is resolved... isn't it?

**Comment by Mystael** [comment] 2022-06-08 15:28
Yes, it is resolved.

**Comment by mercmobily** [comment] 2022-06-08 23:05
How come the issue is still marked as open?

**Comment by zainafzal08** [comment] 2022-06-09 00:52
Good point, closing.

**Closed by zainafzal08** 2022-06-09 00:52 UTC
