### ISSUE TITLE
Have it available for kiosk mode

### ISSUE THREAD

**Issue by Ej17** [GoogleChromeLabs/text-app#480] opened 2019-11-05 11:45 UTC
Want to try and use the extension on Chromebooks for exam users in kiosk mode, as a way for users to sit exams without having access to the internet using a text editor only. (A bit like notepad in windows).

**Comment by BugsNash** [comment] 2019-11-05 23:04
Duplicate of #389, but thank you for the extra context! This does seem like a worthwhile use case.

**Closed by BugsNash** 2019-11-05 23:04 UTC

**Comment by BugsNash** [comment] 2019-11-06 00:43
This has been fixed and updated on the web store. You should be able to add Text as a kiosk app now

**Comment by BugsNash** [comment] 2019-11-19 00:46
This fix has been reverted due to the issues it introduces with the menu bar still being visible, e.g. #485.

See duplicate issue #389 for more info. In the mean time, if taking notes during an exam is needed, the test app will normally provide a way to do so within the app.
