### ISSUE TITLE
I can't save files from the left-hand menu 'save' option

### ISSUE THREAD

**Issue by cfye14** [GoogleChromeLabs/text-app#251] opened 2014-10-09 20:11 UTC
I can, however, use 'save as' and save over the old file. It's quite annoying to have to do that, obviously. This issue also doesn't seem to apply to all files, and furthermore, if I use the 'save as' option to save over the old file with the same file name, I no longer have the issue.

**Comment by BugsNash** [comment] 2018-06-01 05:11
Hi cfya14 :)

I'm not able to reproduce this issue. Are you able to provide a reproducible test case?

**Comment by BugsNash** [comment] 2018-07-02 01:56
Closing as can't repro. Please reopen if it continues to be an issue.

**Closed by BugsNash** 2018-07-02 01:56 UTC
Labels: needs-feedback
