### ISSUE TITLE
Won't save files

### ISSUE THREAD

**Issue by TechFun4All** [GoogleChromeLabs/text-app#464] opened 2019-05-16 19:40 UTC
I'm coding a website using Text, and the app seems to have developed a bug. I can't seem to save certain files with it, whether using CTRL-S, or the Save or Save As buttons. This is only the case for some files - the rest are fine.

The * for unsaved changes does not go away, and when I try to close the program, it asks if I want to save changes, but then I can't. Also, I've checked using different software, and the changes are definitely not being saved.

Also, if it helps, most of the unsaving files (some save fine) don't have file extensions.

Thanks in advance.

**Comment by BugsNash** [comment] 2019-05-16 23:14
Hi TechFun4All, thanks for reporting :) 

Can you reliably reproduce this issue with the same file? If so can you please attach the file so I can try to reproduce?

**Comment by TechFun4All** [comment] 2019-05-19 13:03
Hi BugsNash,

Thanks for responding so quickly!

I've attached my about page for the website, which is one of the files not saving. Unfortunately Github can't accept the files without an extension, so I've attached it as a .txt file. However, it seems to be able to save it when in .txt form.

[about.txt](https://github.com/GoogleChromeLabs/text-app/files/3195089/about.txt)

Just so you know, the bug seemed to particularly develop when I copied all the .html files over to files without file extensions, for better URLs on the website. Also, the files are located in the Chromebook Linux files area, which (as you may already know) is a Beta addition to Chrome OS, which effectively adds an accessible Linux terminal.

Thanks for helping :D

**Comment by BugsNash** [comment] 2019-05-22 00:10
Thanks for the file! I'm not able to reproduce this issue.

Steps I took: on a pixelbook running Chrome OS 74.0.3729.159 64-bit I downloaded the file you linked, removed the extension (now named 'about') and moved it to the Linux files directory. I opened it in the text app, made a change, and was able to save the file normally. After closing and reopening the file the change has persisted.

Have you tried editing the same files in the Linux files area with some other software to see if it's just the Text app that this is happening on? Have you tried uninstalling and reinstalling the Text app? Have you tried restarting to force a remount of the Linux files area?

**Comment by markstos** [comment] 2019-05-31 13:09
@TechFun4All You might also consider configuring your web server to serve "about.html" as "/about" without renaming the file.

**Comment by TechFun4All** [comment] 2019-06-19 16:35
@BugsNash thanks for trying! I haven't done everything you suggested, I'll give that a go. :)

**Comment by TechFun4All** [comment] 2019-06-19 16:36
@markstos Thanks for your suggestion, I hadn't thought of that, obvious as it is!

**Comment by BugsNash** [comment] 2019-08-28 20:58
Closing this issues as it's not reproducible. If the problem is in fact caused by moving the files mid edit then that's probably working as intended. If that's functionality that people want feel free to open another issue :)

**Closed by BugsNash** 2019-08-28 20:58 UTC
Labels: bug, needs-feedback
