### ISSUE TITLE
cut and paste functions

### ISSUE THREAD

**Issue by renifulton** [GoogleChromeLabs/text-app#284] opened 2015-10-30 17:16 UTC
unable to cut or copy. only paste function available. this seems to be a new problem that I have not been able to resolve. and there is no print function but I'm not sure there ever was as I never tried printing from text but it was a desperate move to try to save the work I did off line in text.

**Comment by tarcey** [comment] 2015-12-18 11:33
Same issue here, right-clicking unmarks any previously highlighted/marked text, making the cut/copy function (or any right-click function on highlighted text) unavailable. Keyboard shortcuts for cut/copy still work as expected, since they do not involve right-clicking

**Comment by jostmey** [comment] 2016-01-16 18:24
I have the same problem.

After opening a file from the "Downloads" folder, I discovered that I cannot copy text after I highlight it. Instead, the highlights over the disappear.

As an aside, I love this text editor! It is by far the best, simplest looking editor out there. Thanks!

**Comment by BugsNash** [comment] 2018-06-18 03:14
Duplicate of #282

**Closed by BugsNash** 2018-06-18 03:14 UTC
